---
development:
  cloud_name: myph
  api_key: '947592384671168'
  api_secret: Ps-PpJCAEdNNKgki4D7iw-C77zw
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: myph
  api_key: '947592384671168'
  api_secret: Ps-PpJCAEdNNKgki4D7iw-C77zw
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: myph
  api_key: '947592384671168'
  api_secret: Ps-PpJCAEdNNKgki4D7iw-C77zw
  enhance_image_tag: true
  static_image_support: false
